[package]
name = "nachtwacht-frontend"
version = "0.2.0"
edition = "2021"
license = "AGPLv3"
description = "This is the frontend webapp server to configure and inspect N8w8."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
actix-files = "0.6.2"
actix-session = {version="0.7.2", features=["cookie-session"]}
log = "0.4.17"
env_logger = "0.10.0"
async-stream = "0.3.3"
prost = "0.11.3"
protobuf = "2.27.1"
