variables:
  RUST_BEFORESCRIPT: "apt-get update -yqq; apt-get install -yqq --no-install-recommends protobuf-compiler"
  PACKAGECLOUD_REPOSITORY: "lexxy23/ds2-rpm"

sast:
  stage: test

include:
  - project: 'ds_2/ci-templates'
    ref: develop
    file:
      - '/templates/stages.yaml'
      - '/templates/global-vars.yaml'
      - '/templates/build-rust.yaml'
      - '/templates/deploy-adoc.yaml'
      - '/templates/deploy-azure.yaml'
      - '/templates/check-license.yaml'
      - '/templates/generate-sbom-cyclonedx.yaml'
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

package-debug-rpm:
  extends: .package-debug-rpm-ol8

package-release-rpm:
  extends: .package-release-rpm-ol8

deploy-debug-rpm-azure:
  extends: .deploy-azure
  rules:
    - if: $CI_COMMIT_BRANCH
  dependencies:
    - package-debug-rpm

#deploy-debug-rpm-ol8-packagecloud:
#  extends: .deploy-rpm-packagecloud
#  dependencies:
#    - package-debug-rpm
#  rules:
#    - if: $CI_COMMIT_BRANCH
#  variables:
#    PACKAGECLOUD_PUSHSTRING: "ol/8"

deploy-release-rpm-azure:
  extends: .deploy-azure
  rules:
    - if: $CI_COMMIT_TAG
  dependencies:
    - package-release-rpm
