variables:
  RUST_BEFORESCRIPT: "apt-get update -yqq; apt-get install -yqq --no-install-recommends protobuf-compiler"
  PACKAGECLOUD_REPOSITORY: "lexxy23/ds2-rpm"

sast:
  stage: test

include:
  - project: 'ds_2/ci-templates'
    ref: v0.1.19-alpha.1
    file:
      - '/templates/stages.yaml'
      - '/templates/global-vars.yaml'
      - '/templates/build-rust.yaml'
      - '/templates/deploy-adoc.yaml'
      - '/templates/deploy-azure.yaml'
      - '/templates/check-license.yaml'
      - '/templates/generate-sbom-cyclonedx.yaml'
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

package-debug-rpm:
  extends: .package-debug-rpm-el8

package-release-rpm:
  extends: .package-release-rpm-el8

deploy-debug-rpm-azure:
  extends: .deploy-azure
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
  dependencies:
    - package-debug-rpm

deploy-debug-rpm-ol8-packagecloud:
  extends: .deploy-packagecloud
  dependencies:
    - package-debug-rpm
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
  variables:
    PACKAGECLOUD_PUSHSTRING: "ol/8 el/8"
    ARTIFACTS_PATTERN: "*.el8.x86_64.rpm"
    IS_MASKED_BASE64: 1

deploy-release-rpm-azure:
  extends: .deploy-azure
  rules:
    - if: $CI_COMMIT_TAG
  dependencies:
    - package-release-rpm
