image: "rust:latest"

variables:
  RUST_BEFORESCRIPT: "apt-get update -yqq; apt-get install -yqq --no-install-recommends protobuf-compiler"

sast:
  stage: test

container_scanning:
  variables:
    CS_ANALYZER_IMAGE: registry.gitlab.com/security-products/container-scanning/grype:4

include:
  - project: 'ds_2/ci-templates'
    ref: v0.1.9
    file:
      - '/templates/stages.yaml'
      - '/templates/build-rust.yaml'
      - '/templates/deploy-adoc.yaml'
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
