repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
#      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-toml
      - id: no-commit-to-branch
        args: [ '--pattern', '^(?!((main|develop)|(((fix|feature)\/[a-z0-9][a-z0-9A-Z\-]{1,30}))$)).*' ]
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
