[package]
name = "nachtwacht-orm"
version = "0.3.0-alpha.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = { version = "1.0.0", features = [ "sqlx-postgres", "runtime-actix-rustls", "macros" ] }
nachtwacht-models = { path = "../models" }
serde = "1.0.216"
futures = "0.3.31"
tracing = "0.1.40"
