[package]
name = "nachtwacht-orm"
version = "0.1.1-rc.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = { version = "^0", features = [ "sqlx-postgres", "runtime-actix-rustls", "macros" ] }
nachtwacht-models = { path = "../models" }
log = "0.4.17"
serde = "1.0.145"
