[package]
name = "nachtwacht-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nachtwacht-checks = { path = "../checks" }
nachtwacht-models = { path = "../models" }
log = "0.4.17"
clap = { version = "3.2.2", features = ["derive"] }
http_req = "0.8.1"
env_logger = "0.9.0"

[[bin]]
name="nachtwacht-http-check"
path= "src/http-check-bin.rs"
