[package]
name = "nachtwacht-checks"
version = "0.1.1-rc.1"
edition = "2021"
license = "GPLv3"
description = "This package contains the implementations for all tests."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
chrono = "0.4.19"
reqwest = { version = "0.11.12", features = ["blocking"] }
url = "2.3.1"
nachtwacht-models = { path = "../models" }
log = "0.4.17"
base64 = "0.13.0"
