[package]
name = "nachtwacht-checks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
chrono = "0.4.19"
reqwest = { version = "0.11.11", features = ["blocking"] }
url = "2.2.2"
nachtwacht-models = { path = "../models" }
log = "0.4.17"
base64 = "0.13.0"
