//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub state: i64,
    pub created: DateTimeWithTimeZone,
    pub created_by: Uuid,
    pub modified: Option<DateTimeWithTimeZone>,
    pub modified_by: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::CreatedBy",
        to = "super::account::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Account2,
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::ModifiedBy",
        to = "super::account::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Account1,
    #[sea_orm(
        belongs_to = "super::state::Entity",
        from = "Column::State",
        to = "super::state::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    State,
    #[sea_orm(has_many = "super::roles_to_accounts::Entity")]
    RolesToAccounts,
}

impl Related<super::state::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::State.def()
    }
}

impl Related<super::roles_to_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RolesToAccounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
