name: build workspace

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: build 2
    runs-on: ubuntu-22.04
    env:
      # Share the target dir to try to cache a few build-time deps.
      CARGO_TARGET_DIR: target
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install Protocol Buffers
        run: |
          apt-get install -yqq --no-install-recommends protobuf-compiler
          protoc --version
          rm -rf protoc.zip
      - run: cargo build --workspace
      - run: cargo test
