name: build workspace

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: build 2
    runs-on: ubuntu-22.04
    env:
      # Share the target dir to try to cache a few build-time deps.
      CARGO_TARGET_DIR: target
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install Protocol Buffers
        run: |
          sudo apt update
          sudo apt install -y unzip
          PROTOC_VERSION=$(curl -s "https://api.github.com/repos/protocolbuffers/protobuf/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
          curl -Lo protoc.zip "https://github.com/protocolbuffers/protobuf/releases/latest/download/protoc-${PROTOC_VERSION}-linux-x86_64.zip"
          sudo unzip -q protoc.zip bin/protoc -d /usr/local
          sudo chmod a+x /usr/local/bin/protoc
          protoc --version
          rm -rf protoc.zip
      - run: cargo build --workspace
      - run: cargo test
